#' Lock and unlock directories
#'
#' Mark directories as locked or unlocked for thread-safe processing,
#' using a standard naming scheme for the lock files.
#'
#' @inheritParams touchDirectory
#' @param ... Further arguments to pass to \code{\link{lock}}.
#' @param handle The lock handle generated by \code{\link{lockDirectory}}.
#' 
#' @return 
#' \code{lockDirectory} returns a pair of lock handles, generated by the \pkg{filelock} package.
#'
#' \code{unlockDirectory} unlocks the two handles generated by \code{lockDirectory}.
#'
#' @details
#' \code{lockDirectory} actually creates two locks.
#' The first represents a lock on the versioned directory (i.e., \code{basename(path)}) within the package cache (i.e., \code{dirname(path)}) and provides thread-safe read/write on its contents.
#' Concurrent read operations are also permitted by setting \code{exclusive=FALSE} in \code{...} to define a shared lock..
#' 
#' The second lock is applied to the package cache and is always a shared lock, regardless of the contents of \code{...}.
#' This provides thread-safe access to the lock file used in the first lock,
#' protecting it from deletion when the relevant directory expires in \code{\link{clearDirectories}}.
#'
#' If \code{dirname(path)} does not exist, it will be created by \code{lockDirectory}.
#'
#' @author Aaron Lun
#' 
#' @examples
#' # Creating the relevant directories.
#' cache.dir <- tempfile(pattern="expired_demo")
#' version <- package_version("1.11.0")
#' 
#' handle <- lockDirectory(file.path(cache.dir, version))
#' handle
#' unlockDirectory(handle)
#'
#' list.files(cache.dir)
#' 
#' @export
#' @importFrom filelock lock
lockDirectory <- function(path, ...) {
    dir <- dirname(path)
    dir.create(dir, showWarnings=FALSE)
    plock <- .plock_path(dir)

    second <- lock(plock, exclusive=FALSE) # define this first to protect the other lock.
    vlock <- .vlock_path(path)
    list(lock(vlock, ...), second)
}

lock.suffix <- "-00LOCK"

.unslash <- function(path) {
    sub("/$", "", path)
}

.vlock_path <- function(path) {
    paste0(.unslash(path), lock.suffix)
}

.plock_path <- function(dir) { 
    file.path(dir, paste0("central", lock.suffix))
}

#' @export
#' @importFrom filelock unlock
#' @rdname lockDirectory
unlockDirectory <- function(handle) {
    # Unlock the first one while the second lock on the 'path' directory is
    # still in place to protect the lock file.
    unlock(handle[[1]]) 
    unlock(handle[[2]])
}
