#' Lock and unlock directories
#'
#' Mark directories as locked or unlocked for thread-safe processing.
#' This uses a standard naming scheme for consistency across various applications.
#'
#' @inheritParams touchDirectory
#' @param ... Further arguments to pass to \code{\link{lock}}.
#' @param handle The lock handle generated by \code{\link{lockDirectory}}.
#' 
#' @return 
#' \code{lockDirectory} returns a pair of lock handles, generated by the \pkg{filelock} package.
#'
#' \code{unlockDirectory} unlocks the two handles generated by \code{lockDirectory}.
#'
#' @details
#' \code{lockDirectory} actually creates two locks.
#' The first represents a lock on the \code{version} subdirectory within \code{path} and provides thread-safe read/write on its contents.
#' Concurrent read operations are also permitted by setting \code{exclusive=FALSE} in \code{...} to define a shared lock..
#' 
#' The second lock is applied to \code{path} and is always a shared lock, regardless of the contents of \code{...}.
#' This provides thread-safe access to the lock file used in the first lock,
#' protecting it from deletion when the relevant directory expires in \code{\link{clearDirectories}}.
#'
#' @author Aaron Lun
#' 
#' @examples
#' # Creating the relevant directories.
#' base.path <- tempfile(pattern="expired_demo")
#' dir.create(base.path)
#' version <- package_version("1.11.0")
#' 
#' handle <- lockDirectory(base.path, version)
#' handle
#' unlockDirectory(handle)
#' 
#' @export
#' @importFrom filelock lock
lockDirectory <- function(path, version, ...) {
    plock <- .plock_path(path)
    second <- lock(plock, exclusive=FALSE) # define this first to protect the other lock.
    vlock <- .vlock_path(path, version)
    list(lock(vlock, ...), second)
}

lock.suffix <- "-00LOCK"

.vlock_path <- function(path, version) {
    file.path(path, paste0(as.character(version), lock.suffix)) 
}

.plock_path <- function(path) { 
    file.path(path, paste0("central", lock.suffix))
}

#' @export
#' @importFrom filelock unlock
#' @rdname lockDirectory
unlockDirectory <- function(handle) {
    # Unlock the first one while the second lock on the 'path' directory is
    # still in place to protect the lock file.
    unlock(handle[[1]]) 
    unlock(handle[[2]])
}
