#' Lock and unlock directories
#'
#' Mark directories as locked or unlocked for thread-safe processing.
#' This uses a standard naming scheme for consistency across various applications.
#'
#' @inheritParams touchDirectory
#' @param ... Further arguments to pass to \code{\link{lock}}.
#' @param handle The lock handle generated by \code{\link{lockDirectory}}.
#' 
#' @return 
#' \code{lockDirectory} returns a lock handle from the \pkg{filelock} package,
#' applied to a lock file that uses \code{version} as its prefix.
#'
#' \code{unlockDirectory} unlocks the file referenced by the lock handle.
#'
#' @author Aaron Lun
#' 
#' @examples
#' # Creating the relevant directories.
#' base.path <- tempfile(pattern="expired_demo")
#' dir.create(base.path)
#' version <- package_version("1.11.0")
#' 
#' handle <- lockDirectory(base.path, version)
#' handle
#' unlockDirectory(handle)
#' 
#' @export
#' @importFrom filelock lock
lockDirectory <- function(path, version, ...) {
    flock <- file.path(path, paste0(as.character(version), "-00LOCK"), ...)
    lock(flock)
}

#' @export
#' @importFrom filelock unlock
#' @rdname lockDirectory
unlockDirectory <- function(handle) {
    unlock(handle)
}
